version: "3.8"
services:
  spring-backend:
    build:
      context: ./spring-backend/movie-ticket-booking  # Path to your Spring Boot Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/movie-ticket-booking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nibin123
    depends_on:
      - postgres
    networks:
      - backend-network

  react-frontend:
    build:
      context: ./react-frontend/movie-ticket-booking  # Path to your React Dockerfile
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - backend-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: movie-ticket-booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nibin123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
