spring.application.name=movie-ticket-booking
spring.datasource.url=jdbc:postgresql://localhost:5432/movie-ticket-booking
spring.datasource.username=postgres
spring.datasource.password=nibin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true